### ISSUE TITLE
`pip install` of github HEAD fails with "No module named 'Cython'"

### ISSUE THREAD

**Issue by tartley** [sseemayer/Py2D#11]
Py2D is wonderful, thank you for it!

Pip-installing the current github HEAD, for example using:

    pip install git+git://github.com/sseemayer/Py2D#egg=Py2D

fails, with:

```
      File "/tmp/pip-build-486gjgiq/Py2D/setup.py", line 4, in <module>
        from Cython.Distutils import build_ext
    ModuleNotFoundError: No module named 'Cython'
```

When pip starts installing, it first imports setup.py before it has installed anything, so no third-party packages such as Cython are available. For this reason, setup.py should never import anything other than the standard library.

Back when you wrote this code, though, this was the Cython's recommended usage (it still is, according to their documentation.), to be side-stepped by manually installing 'Cython' before installing Py2D.

However setuptools now supports a better way. PR imminent...

**Comment by sseemayer** [comment]
Thanks for your PR! I guess this fixes your issue?

**Comment by tartley** [comment]
Yes, that's the intent. It works for me.
